### ISSUE TITLE
Update to module

### ISSUE THREAD

**Issue by spendres** [zheksoon/dioma#1]
Nice library!

`yarn test` returns:

> The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

...followed by success of all tests.

adding "type": "module", to package.json clears the warning.

**Comment by zheksoon** [comment]
Thanks! Will do today/this week 👍

**Comment by zheksoon** [comment]
> Nice library!
> 
> `yarn test` returns:
> 
> > The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
> 
> ...followed by success of all tests.
> 
> adding "type": "module", to package.json clears the warning.

Fixed in v0.3.4

Thanks for reporting!
