### ISSUE TITLE
Can `inject` in a class constructor be relative to the container context that initializes it ?

### ISSUE THREAD

**Issue by olup** [zheksoon/dioma#6]
That's maybe a nonsensical question.

I instantiate a container for every web request I take in a controller. The container is created inside the web callback, so I don't have access to it in the global scope where I would need it to inject classes in my constructors.

I guess I need to register every class of my app against this instance of a container. 

What would be just cool is a way to `inject`call in my classes constructor against the container used by the parent class.

Does that even make sense ? And if so, is that maybe too much magic ?

Promising projact anyway, I have been looking for a no-nonsense DI lib for some time (even built one myself). My goal is to use it in the context of cloudflare workers, where env and services are injected as parameters to the initial fetch call.

**Comment by olup** [comment]
Just had the idea to use asyncLocalStorage to pass the container to the context and use the `inject` from the asyncLocalStorage.getStore in the constructors 👍

**Comment by zheksoon** [comment]
Hi!
This question definitely makes sense :)
So, if you are instantiating a new container, for sure you need a way to carry it over from one injected class to another. You can do this using injection with arguments, like this:

```typescript
import { Container, Scopes } from "dioma";

const requestHandler = (req, res) => {
  const container = new Container();

  const classA = container.inject(ClassA, container);
};

class ClassA {
  constructor(
    private container: Container,
    private b = container.inject(ClassB, container),
    private c = container.inject(ClassC)
  ) {}

  static scope = Scopes.Transient();
}

class ClassB {
  constructor(private container: Container, private c = container.inject(ClassC)) {}

  static scope = Scopes.Resolution();
}

class ClassC {
  constructor() {}

  static scope = Scopes.Container();
}
```

But for sure you can use any other methods of sharing the container instance in the request handler live cycle

**Comment by olup** [comment]
A yes, I tried this, but I had no services I wanted to make transient. But then I could indeed just have the first layer transient, as you proposed. Thanks for sharing this, and thanks for the cool lib, I think it's a great match with Cloudflare workers based projects.

**Comment by zheksoon** [comment]
Thanks! :)

**Comment by zheksoon** [comment]
Hi, sorry for the delay. So, resolution scope is like transient scope, but inside one injection it returns the same instance. Like this:
```
    class A {
      constructor(public firstB = inject(B), public secondB = inject(B)) {}

      static scope = Scopes.Singleton();
    }

    class B {
      static scope = Scopes.Resolution();
    }

    const a = inject(A);

    console.log(a.firstB === a.secondB); // true
   ```
   While transient scope would give you different instances of `B`
