### ISSUE TITLE
Types exports are wrong in package.json

### ISSUE THREAD

**Issue by marcomuser** [zheksoon/dioma#9]
According to [Are The Types Wrong](https://arethetypeswrong.github.io/?p=dioma) the types for dioma are not set up correctly. The main issue is that the exports property in package.json defines only one type for both the .cjs as well as the .js file:
```
"exports": {
    ".": {
      "import": "./dist/dioma.js",
      "require": "./dist/dioma.cjs",
      "types": "./dist/index.d.ts"
    }
  },
```

This is, however, not possible. It needs to export a separate type file for each:
```
"exports": {
    ".": {
      "import": {
        "types": "./dist/dioma.d.ts",
        "default": "./dist/dioma.js"
      },
      "require": {
        "types": "./dist/dioma.d.cts",
        "default": "./dist/dioma.cjs"
      }
    },
```
Note that the types property needs to come first and that the file extension of the types need to match (e.g. .cts and .cjs).

I would also suggest to point the main property export to the ESM export as the package.json defines that this package is an es module.

As an example take a look at openapi-fetch for a library that correctly works in both CommonJS as well as ESM in Node.js: https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/package.json.

**Comment by zheksoon** [comment]
Many thanks for reporting! Made it green :) 
<img width="223" alt="Screenshot 2024-04-20 at 14 43 19" src="https://github.com/zheksoon/dioma/assets/8950238/e19585ba-61de-46e8-94a3-877525add76d">
